### ISSUE TITLE
Does not build on Mac.

### ISSUE THREAD

**Issue by erwindassen** [ava-labs/mnemonic-shamir-secret-sharing-cli#2]
Trying to build following instructions on the latest MacOS (Ventura 13.4.1) gives:

```
❯ make
make: clang++-10: No such file or directory
make: *** [build/.//Utils/Utils.o] Error 1
```

I have Xcode CLI tools installed and clang is version:

```
❯ clang++ -v
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

I guess it is just not supported. Would be cool to have it.

**Comment by itinance** [comment]
This happens even on Ubuntu

`make: clang++-10: No such file or directory`

**Comment by itinance** [comment]
I changed `CXX := clang++-10` within the Makefile into `CXX := clang++` and with that it's building

**Comment by itinance** [comment]
@erwindassen you can start Ubuntu via Docker on your Mac and SSH into it:

```
docker pull ubuntu
docker run -ti --rm ubuntu /bin/bash
```

After that, modify the Makefile as shown in #4  and you can use it :)
